function tasksOnceFileOpen(a,c){closeFile.disabled=!1;noFileSelected.hidden=!0;document.querySelector(`#${a}`).hidden=!1;null!==document.querySelector(`#${c}`)?(fileName.innerHTML=document.querySelector(`#${c}`).value.replace("C:\\fakepath\\",""),fileSize.innerHTML=`${(event.target.files[0].size/1048576).toFixed(2)}MB`,fileLastModified.innerHTML=(new Date(event.target.files[0].lastModified)).toString().slice(0,21)):viewerStatusBarIndicator.hidden=!0;"---"!==fileName.innerHTML&&fileViewingHistoryNames.push(fileName.innerHTML);
fileViewingHistoryTimes.push(get12HourTime());hideViewing.disabled=!1}
function closeCurrentFile(){additionalVideoControls.hidden=!0;anotherNoteView.hidden=!0;anotherNoteViewer.hidden=!0;anotherNoteViewQuill.setContents();chooseViewer.hidden=!1;closeFile.disabled=!0;cloudFileView.hidden=!0;cloudFileView.removeAttribute("src");cloudFileViewer.hidden=!0;codeFileView.hidden=!0;codeFileViewer.hidden=!0;codeFileViewerStatusBar.hidden=!0;customEmbedViewer.hidden=!0;imageView.hidden=!0;imageView.removeAttribute("src");imageViewer.hidden=!0;markdownFileView.hidden=!0;markdownFileView.removeAttribute("src");
markdownFileViewer.hidden=!0;noFileSelected.hidden=!1;onlineDesignView.hidden=!0;onlineDesignView.removeAttribute("src");onlineDesignViewer.hidden=!0;pdfView.hidden=!0;pdfView.removeAttribute("src");pdfViewer.hidden=!0;textView.hidden=!0;textView.innerHTML="";textViewActions.hidden=!0;textViewer.hidden=!0;tubeVideoView.hidden=!0;tubeVideoView.removeAttribute("src");tubeVideoViewer.hidden=!0;URLToTubeVideo.removeAttribute("value");videoView.hidden=!0;videoView.pause();videoView.removeAttribute("src");
videoViewer.hidden=!0;viewersContainer.hidden=!0;viewerStatusBarIndicator.hidden=!1;webpageURLBar.removeAttribute("value");webpageView.hidden=!0;webpageView.src="Pages/noWebpageNavigated.html";webpageViewer.hidden=!0;wordDocumentView.hidden=!0;wordDocumentView.innerHTML="";wordDocumentViewer.hidden=!0;fileName.innerHTML="---";fileSize.innerHTML="---";fileLastModified.innerHTML="---";hideViewing.disabled=!0}
function readTextFile(){const a=new FileReader;a.onload=()=>{textView.innerHTML=a.result};a.readAsText(event.target.files[0])}
function readWordDocument(){const a=new FileReader;a.onload=c=>{mammothPlus.convertToHtml({arrayBuffer:c.target.result},mammothJSOptions).then(b=>{wordDocumentView.innerHTML=b.value;displaySnackbar("Some formatting may not display correctly")}).catch(()=>{throwAppError("The file you are trying to view does not seem like a Word document. Ensure the file extension is correct and try again.");closeCurrentFile()})};a.readAsArrayBuffer(event.target.files[0])}
function readMarkdownFile(){const a=new FileReader;a.onload=()=>{markdownFileView.innerHTML=marked.parse(a.result)};a.readAsText(event.target.files[0])}function readHTMLNote(){const a=new FileReader;a.onload=()=>{anotherNoteViewQuill.clipboard.dangerouslyPasteHTML(a.result)};a.readAsText(event.target.files[0]);tasksOnceFileOpen("anotherNoteView","anotherNoteFileInput")}
function viewCodeFile(){const a=new FileReader;a.onload=()=>{codeFileViewCodeEditor.session.setValue(a.result)};a.readAsText(event.target.files[0]);codeFileViewerStatusBar.hidden=!1;tasksOnceFileOpen("codeFileView","codeFileInput")}function checkURLInput(a){return""===document.querySelector(`#${a}`).value?(displaySnackbar("Please enter a valid URL"),!1):!0}
function parseCloudDocumentURL(){if(checkURLInput("URLToCloudFile")){if(onedriveOrigin.checked){var a=URLToCloudFile.value.split(""),c="";for(var b=0;b<a.length;b++)if("&"===a[b]&&"a"===a[b+1]&&"c"===a[b+2]&&"t"===a[b+3]&&"i"===a[b+4]&&"o"===a[b+5]&&"n"===a[b+6])for(;;)if(b!==a.length)a[b]="",b++;else break;for(b=0;b<a.length;b++)c+=a[b];toggleDialog(!1,"insertCloudURLDialog",null);cloudFileView.src=`${c}&action=embedview`}else{a=URLToCloudFile.value.replace("https://docs.google.com/","").replace("https://drive.google.com",
"").split("");c="";for(b=0;b<a.length;b++)if("/"===a[b-1]&&"d"===a[b]&&"/"===a[b+1])for(;;)if("/"!==a[b+2])c+=a[b],b++;else{c+=a[b];c+=a[b+1];break}""===c?(toggleDialog(!1,"insertCloudURLDialog",null),throwAppError("This Google Drive document URL is invalid. Please ensure you are copying the link to it from your browser's address bar and try again."),closeCurrentFile()):(toggleDialog(!1,"insertCloudURLDialog",null),cloudFileView.src=`https://docs.google.com/viewer?srcid=${c.replace("d/","")}&pid=explorer&efh=false&a=v&chrome=false&embedded=true`)}toggleViewer(!0,
"cloudFileViewer");tasksOnceFileOpen("cloudFileView",null);addHistoryEntry("URLToCloudFile")}}
function verifyIfiFrameInEmbed(){embeddedCode.value.includes("</iframe>")?(customEmbedViewer.innerHTML=embeddedCode.value,noFileSelected.hidden=!0,viewerStatusBar.hidden=!0,toggleDialog(!1,"customEmbed",null),toggleViewer(!0,"customEmbedViewer"),dynamicallySetHeight(),tasksOnceFileOpen(null,null)):throwAppError("The pasted code does not seem to be an iFrame element. Please ensure the content you are trying to embed is within an element of this type.")};
