const quill=new Quill("#mainEditor",{modules:{toolbar:toolbarOptions},placeholder:'"Everything begins with an idea" - Earl Nightingale',theme:"snow"}),anotherNoteViewQuill=new Quill("#anotherNoteView",{readOnly:!0,modules:{toolbar:null},theme:"snow"}),copyHistoryQuill=new Quill("#copyHistoryEditor",{readOnly:!0,modules:{toolbar:null},theme:"snow"}),insertTableQuill=new Quill("#insertTableEditor",{readOnly:!0,modules:{toolbar:null},placeholder:"You haven't created a table yet",theme:"snow"});noteHTMLCodeEditor.session.setMode("ace/mode/html");
noteHTMLCodeEditor.setReadOnly(!0);noteHTMLCodeEditor.session.setUseWrapMode(!0);codeFileViewCodeEditor.session.setMode("ace/mode/plain_text");codeFileViewCodeEditor.setReadOnly(!0);codeFileViewCodeEditor.session.setUseWrapMode(!0);function shiftProgressValue(a,b,c,d){b<c&&(document.querySelector(`#${a}`).value=b,setTimeout(shiftProgressValue,1,a,b+d,c,d))}
function dynamicallySetHeight(){appSectionsTable.style.height=adjustedHeight;anotherNoteView.style.height=adjustedHeight;wordDocumentView.style.height=adjustedHeight;noteEditor.style.height=adjustedHeight;codeFileView.style.height=adjustedHeight;for(let a=0;a<iframes.length;a++)iframes[a].style.height=window.innerHeight+"px"}function hideAndShow(a,b){document.querySelector(`#${a}`).hidden=!0;document.querySelector(`#${b}`).hidden=!1}
function alterWindowTitle(a){document.title=a?`Home - ${appName}`:""===noteName.value?`Untitled - ${appName}`:`${noteName.value} - ${appName}`}function toggleViewer(a,b){document.querySelector(`#${b}`).hidden=!a;viewersContainer.hidden=!a;chooseViewer.hidden=a}function toggleDialog(a,b,c){dialogFocusBackground.hidden=!a;document.querySelector(`#${b}`).hidden=!a;null!==c&&document.querySelector(`#${c}`).focus()}
function toggleMenuCheck(a){document.querySelector(`#${a}`).src.includes(checkedImageSource)?document.querySelector(`#${a}`).src=uncheckedImageSource:document.querySelector(`#${a}`).src=checkedImageSource}
function alterMenuFunctions(a){document.querySelector("#closeNote").disabled=a;document.querySelector("#downloadAsPlainText").disabled=a;document.querySelector("#downloadNote").disabled=a;document.querySelector("#hideEditor").disabled=a;document.querySelector("#insertDate").disabled=a;document.querySelector("#insertOnlineImageButton").disabled=a;document.querySelector("#insertSymbolButton").disabled=a;document.querySelector("#insertTableButton").disabled=a;document.querySelector("#insertTime").disabled=
a;document.querySelector("#printNote").disabled=a;document.querySelector("#quillRedo").disabled=a;document.querySelector("#quillUndo").disabled=a;document.querySelector("#save").disabled=a;document.querySelector("#saveForLater").disabled=a;document.querySelector("#showHTMLEditor").disabled=a}
function applyPercentageSizes(){chooseViewer.style.width=`${viewingSize.value}%`;viewersContainer.style.width=`${viewingSize.value}%`;createOrOpenContainer.style.width=`${editorSize.value}%`;noteEditor.style.width=`${editorSize.value}%`}
function adjustViewingAndEditorSizes(){viewingSize.value>viewingSize.max?viewingSize.value=viewingSize.max:viewingSize.value<viewingSize.min&&(viewingSize.value=viewingSize.min);editorSize.value=100-viewingSize.value;applyPercentageSizes();localStorage.setItem("viewingSizeValue",viewingSize.value)}function addHistoryEntry(a){fileViewingHistoryNames.push(document.querySelector(`#${a}`).value);fileViewingHistoryTimes.push(get12HourTime())}
function appendViewingHistory(){viewingHistoryTable.innerHTML="";var a=document.createElement("tr"),b=document.createElement("td"),c=document.createElement("td");b.innerHTML="<b>Time</b>";c.innerHTML="<b>Document</b>";a.appendChild(b);a.appendChild(c);viewingHistoryTable.appendChild(a);for(a=0;a<fileViewingHistoryNames.length;a++){b=document.createElement("tr");c=document.createElement("td");const d=document.createElement("td");c.innerHTML=fileViewingHistoryTimes[a];d.innerHTML=fileViewingHistoryNames[a];
b.appendChild(c);b.appendChild(d);viewingHistoryTable.appendChild(b)}}function throwAppError(a){toggleDialog(!0,"applicationError",null);errorMessage.innerHTML=a}function displaySnackbar(a){snackbar.style.display="flex";snackbarMessage.innerHTML=a;setTimeout(function(){snackbar.style.display="none"},7500)}
function get12HourTime(){let a,b,c;a=12<currentDate.getHours()?currentDate.getHours()-12:10>currentDate.getHours()?currentDate.getHours().toString().replace("0",""):currentDate.getHours();b=10>currentDate.getMinutes()?"0"+currentDate.getMinutes():currentDate.getMinutes();c=12>currentDate.getHours()?" AM":" PM";return a+":"+b+c}
function createTable(){createdTable.innerHTML="";for(let a=0;a<tableRows.value;a++){const b=document.createElement("tr");for(let c=0;c<tableColumns.value;c++){const d=document.createElement("td");c===tableColumns.value-1&&a===tableRows.value-1&&(d.innerHTML="\u3164");b.appendChild(d)}createdTable.appendChild(b)}insertTableQuill.clipboard.dangerouslyPasteHTML(tableSourceHTML.innerHTML)}
function addUnicodeCharacters(){for(let b=0;b<symbolList.length;b++)for(var a=0;a<symbolList[b].length;){a=document.createElement("div");const c=document.createElement("h3");c.style.textAlign="center";c.innerHTML=symbolList[b][0];a.className="symbolContainer";a.title=symbolList[b][1];a.setAttribute("onclick",`quill.insertText(quill.getSelection(focus), '${symbolList[b][0]}')`);a.appendChild(c);symbolsDisplay.appendChild(a);break}}
function onLoadTasks(){null!==mobileDetect.phone()&&window.location.replace("learn-more");try{"true"===localStorage.getItem("darkMode")&&(darkModeToggle.click(),gettingStartedDarkMode.checked=!0);dynamicallySetHeight();updateStatusBar();addUnicodeCharacters();12>currentDate.getHours()?userGreeting.innerHTML="Good Morning \ud83d\ude0e":12<=currentDate.getHours()&&18>currentDate.getHours()?userGreeting.innerHTML="Good Afternoon \ud83c\udf1e":userGreeting.innerHTML="Good Evening \ud83c\udf1a";"<p></p>"!==
localStorage.getItem("noteProgress")&&null!==localStorage.getItem("noteProgress")&&(hideAndShow("createOrOpenContainer","noteEditor"),quill.clipboard.dangerouslyPasteHTML(localStorage.getItem("noteProgress")),noteName.value=localStorage.getItem("noteTitle"),alterMenuFunctions(!1));"true"!==localStorage.getItem("finishedGetStarted")&&toggleDialog(!0,"gettingStarted",null);null===localStorage.getItem("totalWordCountArray")&&(addedWordCountArray=[],localStorage.setItem("totalWordCountArray",JSON.stringify(addedWordCountArray)));
null===localStorage.getItem("totalCharacterCountArray")&&(addedCharacterCountArray=[],localStorage.setItem("totalCharacterCountArray",JSON.stringify(addedCharacterCountArray)));if(workingURLParameters.has("name")||workingURLParameters.has("markup"))initiateNote(!1),noteName.value=workingURLParameters.get("name"),quill.clipboard.dangerouslyPasteHTML(decodeURIComponent(workingURLParameters.get("markup"))),history.pushState(null,"",window.location.href.split("?")[0]);null!==localStorage.getItem("savedNotes")&&
(savedForLater.innerHTML=localStorage.getItem("savedNotes"),savedForLaterDetails.click(),savedForLaterDetails.open=!0);"true"===localStorage.getItem("autoSaveEnabled")&&autoSave.click();"true"===localStorage.getItem("wordWrapEnabled")&&wordWrap.click();null!==localStorage.getItem("selectedCodeEditorTheme")&&(codeEditorTheme.value=localStorage.getItem("selectedCodeEditorTheme"),noteHTMLCodeEditor.setTheme(`ace/theme/${codeEditorTheme.value}`),codeFileViewCodeEditor.setTheme(`ace/theme/${codeEditorTheme.value}`));
null!==localStorage.getItem("viewingSizeValue")&&(viewingSize.value=localStorage.getItem("viewingSizeValue"),adjustViewingAndEditorSizes());null!==localStorage.getItem("storedTypingTarget")&&("false"===localStorage.getItem("customTarget")?(typingTarget.hidden=!1,typingTarget.value=localStorage.getItem("storedTypingTarget")):"true"===localStorage.getItem("customTarget")&&(customTypingTarget.hidden=!1,customTypingTarget.value=localStorage.getItem("storedTypingTarget")),setTypingTarget.click(),snackbar.style.display=
"none");appLoad.hidden=!0}catch(a){throwAppError(a)}};
